import DarkSelect from "../components/ui/DarkSelect";
import { useCallback, useEffect, useMemo, useState } from "react";
import { BrainCircuit, CheckCircle2, CloudDownload, DatabaseZap, FileCheck2, RefreshCw, RotateCcw, Share2, ShieldCheck } from "lucide-react";
import api from "../services/api";
import { createSocket } from "../services/socket";
import { useAuth } from "../hooks/useAuth";

const modules = ["GHOSTTRACE", "NETGUARD", "AGENTWATCH", "EDGEARMOR", "SARVERIFY", "ROCSHIELD", "RECOVERYSHIELD"];
const badge = { ACTIVE: "text-emerald-300 border-emerald-400/20 bg-emerald-400/10", APPLIED: "text-emerald-300 border-emerald-400/20 bg-emerald-400/10", VALIDATED: "text-cyan-300 border-cyan-400/20 bg-cyan-400/10", HIGH: "text-orange-300 border-orange-400/20 bg-orange-400/10", CRITICAL: "text-red-300 border-red-400/20 bg-red-400/10", PENDING: "text-amber-300 border-amber-400/20 bg-amber-400/10", CANDIDATE: "text-purple-300 border-purple-400/20 bg-purple-400/10", REJECTED: "text-red-300 border-red-400/20 bg-red-400/10", RETIRED: "text-slate-400 border-slate-700 bg-slate-800/50", ROLLED_BACK: "text-amber-300 border-amber-400/20 bg-amber-400/10" };
const today = () => new Date().toISOString().slice(0, 10);
const monthAgo = () => new Date(Date.now() - 30 * 86400000).toISOString().slice(0, 10);

const IntelligenceCenter = () => {
    const { hasPermission, user } = useAuth();
    const [data, setData] = useState({ indicators: [], models: [], deployments: [], reports: [], reportTypes: [], stats: {} });
    const [vessels, setVessels] = useState([]);
    const [tab, setTab] = useState("intelligence");
    const [module, setModule] = useState("GHOSTTRACE");
    const [vessel, setVessel] = useState("");
    const [reportVessel, setReportVessel] = useState("");
    const [reportType, setReportType] = useState("ASSET_INVENTORY");
    const [from, setFrom] = useState(monthAgo()); const [to, setTo] = useState(today());
    const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
    const [error, setError] = useState(""); const [message, setMessage] = useState("");

    const load = useCallback(async () => {
        try {
            setLoading(true); setError("");
            const [overview, vesselResponse] = await Promise.all([api.get("/intelligence"), api.get("/vessels")]);
            setData(overview.data); const next = vesselResponse.data?.vessels || []; setVessels(next); setVessel((current) => current || next[0]?._id || ""); setReportVessel((current) => current || (user?.allVessels ? "" : next[0]?._id || ""));
        } catch (requestError) { setError(requestError.response?.data?.message || "Failed to load Intelligence Center"); }
        finally { setLoading(false); }
    }, [user?.allVessels]);
    useEffect(() => { const timer = window.setTimeout(load, 0); const socket = createSocket(); socket.on("threat-intelligence:new", load); return () => { window.clearTimeout(timer); socket.disconnect(); }; }, [load]);

    const run = async (request, success) => {
        try { setBusy(true); setError(""); setMessage(""); const response = await request(); setMessage(response.data?.message || success); await load(); }
        catch (requestError) { setError(requestError.response?.data?.message || "Operation failed"); }
        finally { setBusy(false); }
    };
    const validateModel = (model) => {
        const precision = window.prompt("Measured precision (0 to 1). Required: 0.90", "0.90"); if (precision === null) return;
        const recall = window.prompt("Measured recall (0 to 1). Required: 0.85", "0.85"); if (recall === null) return;
        const dataset = window.prompt("Evaluation dataset name", "labelled-simulation-v1"); if (!dataset) return;
        run(() => api.post(`/intelligence/learning/${model._id}/validate`, { precision: Number(precision), recall: Number(recall), dataset }), "Validation saved");
    };
    const download = async (report, format) => {
        try { setBusy(true); const response = await api.get(`/intelligence/compliance/reports/${report._id}/${format}`, { responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = `${report.reportId}.${format}`; link.click(); URL.revokeObjectURL(url); }
        catch (requestError) { setError(requestError.response?.data?.message || "Report download failed"); } finally { setBusy(false); }
    };
    const modelRows = useMemo(() => data.models || [], [data.models]);

    return <div className="space-y-5">
        <div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl border border-cyan-400/20 bg-cyan-400/10"><DatabaseZap className="h-5 w-5 text-cyan-400" /></div><div><h1 className="text-2xl font-bold text-white">Intelligence Center</h1><p className="mt-1 text-sm text-slate-400">Fleet threat sharing, versioned learning packs and immutable compliance evidence</p></div></div><button onClick={load} className="flex items-center gap-2 self-start rounded-lg border border-slate-800 bg-slate-900 px-3 py-2 text-xs text-slate-300"><RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} /> Refresh</button></div>
        {error && <div className="rounded-xl border border-red-400/20 bg-red-400/5 p-3 text-sm text-red-300">{error}</div>}{message && <div className="rounded-xl border border-emerald-400/20 bg-emerald-400/5 p-3 text-sm text-emerald-300">{message}</div>}
        <div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><Stat label="Active indicators" value={data.stats?.activeIndicators || 0} /><Stat label="Pending intel syncs" value={data.stats?.pendingIndicatorSyncs || 0} /><Stat label="Active packs" value={data.stats?.activeModels || 0} /><Stat label="Pending deployments" value={data.stats?.pendingModelDeployments || 0} /><Stat label="Locked reports" value={data.stats?.lockedReports || 0} /></div>
        <div className="flex gap-2 border-b border-slate-800">{[["intelligence", "Threat Intelligence"], ["learning", "Fleet Learning"], ["compliance", "Compliance Evidence"]].map(([key, label]) => <button key={key} onClick={() => setTab(key)} className={`border-b-2 px-3 py-3 text-xs ${tab === key ? "border-cyan-400 text-cyan-300" : "border-transparent text-slate-500"}`}>{label}</button>)}</div>

        {tab === "intelligence" && <div className="space-y-4">
            <div className="flex flex-col gap-3 rounded-xl border border-slate-800 bg-slate-950/70 p-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-sm font-semibold text-white">Confirmed-evidence reconciliation</p><p className="mt-1 text-xs text-slate-500">Extracts privacy-safe vectors from all seven defense modules; raw vessel records are never copied.</p></div>{hasPermission("threat-intelligence:manage") && <button disabled={busy} onClick={() => run(() => api.post("/intelligence/reconcile"), "Evidence reconciled")} className="flex items-center gap-2 rounded-lg border border-cyan-400/20 bg-cyan-400/10 px-3 py-2 text-xs text-cyan-300"><Share2 className="h-3.5 w-3.5" /> Reconcile confirmed evidence</button>}</div>
            <div className="overflow-hidden rounded-xl border border-slate-800 bg-slate-950/70"><div className="overflow-x-auto"><div className="min-w-[42rem]"><div className="grid grid-cols-[1fr_.7fr_.5fr_.4fr] border-b border-slate-800 px-4 py-3 text-[10px] uppercase text-slate-600"><span>Indicator</span><span>Module</span><span>Confidence</span><span>Sync</span></div>{!data.indicators?.length ? <div className="p-12 text-center text-sm text-slate-600">No fleet indicators yet. Reconcile confirmed module evidence first.</div> : data.indicators.map((item) => <div key={item._id} className="grid grid-cols-[1fr_.7fr_.5fr_.4fr] items-center border-b border-slate-800/60 px-4 py-3 text-xs"><div className="min-w-0"><p className="truncate font-medium text-slate-200">{item.type}: {item.value}</p><p className="mt-1 truncate text-[10px] text-slate-600">{item.reason}</p></div><span className="text-slate-400">{item.sourceModule}</span><span className="text-slate-300">{item.confidence}% <Badge value={item.severity} /></span><span className="text-amber-300">{item.distributions?.filter((entry) => entry.status === "PENDING").length || 0} pending</span></div>)}</div></div></div>
        </div>}

        {tab === "learning" && <div className="space-y-4">
            <div className="rounded-xl border border-purple-400/15 bg-purple-400/[0.03] p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-end"><label className="flex-1"><span className="mb-2 block text-[10px] uppercase text-slate-500">Defense module</span><DarkSelect value={module} onChange={(event) => setModule(event.target.value)} className="h-10 w-full rounded-lg border border-slate-800 bg-slate-950 px-3 text-xs text-slate-300">{modules.map((item) => <option key={item}>{item}</option>)}</DarkSelect></label>{hasPermission("fleet-learning:manage") && <button disabled={busy} onClick={() => run(() => api.post("/intelligence/learning/candidates", { module }), "Candidate created")} className="flex items-center gap-2 rounded-lg border border-purple-400/20 bg-purple-400/10 px-3 py-2.5 text-xs text-purple-300"><BrainCircuit className="h-3.5 w-3.5" /> Build rule-pack candidate</button>}</div><p className="mt-3 text-[10px] text-slate-600">This phase aggregates confirmed extracted vectors. It does not claim trained ML; measured evaluation is required before activation.</p></div>
            <div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><div className="rounded-xl border border-slate-800 bg-slate-950/70 p-4"><h2 className="text-sm font-semibold text-white">Model lifecycle</h2><div className="mt-4 space-y-3">{modelRows.length === 0 && <p className="py-8 text-center text-xs text-slate-600">No fleet learning packs.</p>}{modelRows.map((item) => <div key={item._id} className="rounded-lg border border-slate-800 bg-slate-900/30 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-semibold text-slate-200">{item.modelKey} v{item.version}</p><p className="mt-1 text-[10px] text-slate-600">{item.patternCount} patterns · {item.learningType.replaceAll("_", " ")}</p></div><Badge value={item.status} /></div>{item.validation?.precision != null && <p className="mt-2 text-[10px] text-slate-400">Precision {(item.validation.precision * 100).toFixed(1)}% · Recall {(item.validation.recall * 100).toFixed(1)}% · {item.validation.dataset}</p>}{hasPermission("fleet-learning:manage") && <div className="mt-3 flex gap-2">{item.status === "CANDIDATE" && <button disabled={busy} onClick={() => validateModel(item)} className="rounded border border-cyan-400/20 px-2 py-1 text-[10px] text-cyan-300">Enter measured validation</button>}{item.status === "VALIDATED" && <button disabled={busy} onClick={() => run(() => api.post(`/intelligence/learning/${item._id}/activate`), "Pack activated")} className="rounded border border-emerald-400/20 px-2 py-1 text-[10px] text-emerald-300">Activate fleet-wide</button>}</div>}</div>)}</div></div>
                <div className="rounded-xl border border-slate-800 bg-slate-950/70 p-4"><h2 className="text-sm font-semibold text-white">Vessel distribution</h2><div className="mt-3 flex gap-2"><DarkSelect value={vessel} onChange={(event) => setVessel(event.target.value)} className="h-9 flex-1 rounded-lg border border-slate-800 bg-slate-950 px-2 text-xs text-slate-300">{vessels.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</DarkSelect>{hasPermission("fleet-learning:manage") && <button disabled={busy || !vessel} onClick={() => run(() => api.post(`/intelligence/vessels/${vessel}/sync`), "Vessel synchronized")} className="rounded border border-cyan-400/20 px-2 text-[10px] text-cyan-300">Sync reconnect</button>}</div><div className="mt-4 space-y-2">{data.deployments?.map((item) => <div key={item._id} className="rounded-lg border border-slate-800 p-3"><div className="flex justify-between gap-2"><div><p className="text-xs text-slate-200">{item.vessel?.name} · {item.modelKey}</p><p className="mt-1 text-[10px] text-slate-600">Current v{item.currentVersion || "-"} · Target v{item.targetVersion || "-"}</p></div><Badge value={item.status} /></div>{hasPermission("fleet-learning:manage") && item.previousVersion && <button disabled={busy} onClick={() => run(() => api.post(`/intelligence/learning/deployments/${item._id}/rollback`), "Deployment rolled back")} className="mt-2 flex items-center gap-1 text-[10px] text-amber-300"><RotateCcw className="h-3 w-3" /> Roll back to v{item.previousVersion}</button>}</div>)}</div></div></div>
        </div>}

        {tab === "compliance" && <div className="space-y-4">
            <div className="rounded-xl border border-emerald-400/15 bg-emerald-400/[0.03] p-4"><div className="grid gap-3 lg:grid-cols-5"><Select label="Report type" value={reportType} onChange={setReportType} options={data.reportTypes || []} /><Select label="Vessel scope" value={reportVessel} onChange={setReportVessel} options={[...(user?.allVessels ? [{ value: "", label: "Entire fleet" }] : []), ...vessels.map((item) => ({ value: item._id, label: `${item.name} (${item.vesselId})` }))]} /><DateField label="From" value={from} onChange={setFrom} /><DateField label="To" value={to} onChange={setTo} /><button disabled={busy || (!reportVessel && !user?.allVessels)} onClick={() => run(() => api.post("/intelligence/compliance/reports", { type: reportType, vessel: reportVessel || null, from, to }), "Report generated")} className="mt-5 flex h-10 items-center justify-center gap-2 rounded-lg border border-emerald-400/20 bg-emerald-400/10 px-3 text-xs text-emerald-300"><FileCheck2 className="h-3.5 w-3.5" /> Generate evidence</button></div><p className="mt-3 text-[10px] text-slate-600">IACS UR E26 structure · SHA-256 evidence hash · MongoDB application-WORM prototype · JSON/PDF exports</p></div>
            <div className="rounded-xl border border-slate-800 bg-slate-950/70"><div className="border-b border-slate-800 p-4"><h2 className="text-sm font-semibold text-white">Immutable evidence vault</h2></div>{!data.reports?.length ? <div className="p-12 text-center text-sm text-slate-600">No compliance reports generated.</div> : <div className="divide-y divide-slate-800/60">{data.reports.map((item) => <div key={item._id} className="flex flex-col gap-3 p-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-emerald-400" /><p className="text-sm font-semibold text-slate-200">{item.reportId}</p><Badge value={item.locked ? "LOCKED" : "UNLOCKED"} /></div><p className="mt-1 text-[10px] text-slate-500">{item.type.replaceAll("_", " ")} · {item.vessel?.name} · {item.summary?.recordCount || 0} records</p><p className="mt-1 font-mono text-[9px] text-slate-700">SHA-256 {item.contentHash}</p></div><div className="flex gap-2"><button disabled={busy} onClick={() => download(item, "json")} className="flex items-center gap-1 rounded border border-cyan-400/20 px-2 py-1 text-[10px] text-cyan-300"><CloudDownload className="h-3 w-3" /> JSON</button><button disabled={busy} onClick={() => download(item, "pdf")} className="flex items-center gap-1 rounded border border-purple-400/20 px-2 py-1 text-[10px] text-purple-300"><CloudDownload className="h-3 w-3" /> PDF</button></div></div>)}</div>}</div>
        </div>}
    </div>;
};

const Stat = ({ label, value }) => <div className="rounded-xl border border-slate-800 bg-slate-950/70 p-4"><CheckCircle2 className="h-4 w-4 text-cyan-400" /><p className="mt-3 text-[10px] uppercase text-slate-600">{label}</p><p className="mt-1 text-2xl font-bold text-white">{value}</p></div>;
const Badge = ({ value }) => <span className={`ml-1 inline-flex rounded-full border px-2 py-0.5 text-[9px] ${badge[value] || "border-slate-700 bg-slate-800/50 text-slate-400"}`}>{String(value).replaceAll("_", " ")}</span>;
const Select = ({ label, value, onChange, options }) => <label><span className="mb-2 block text-[10px] uppercase text-slate-500">{label}</span><DarkSelect value={value} onChange={(event) => onChange(event.target.value)} className="h-10 w-full rounded-lg border border-slate-800 bg-slate-950 px-2 text-xs text-slate-300">{options.map((option) => typeof option === "string" ? <option key={option} value={option}>{option.replaceAll("_", " ")}</option> : <option key={option.value} value={option.value}>{option.label}</option>)}</DarkSelect></label>;
const DateField = ({ label, value, onChange }) => <label><span className="mb-2 block text-[10px] uppercase text-slate-500">{label}</span><input type="date" value={value} onChange={(event) => onChange(event.target.value)} className="h-10 w-full rounded-lg border border-slate-800 bg-slate-950 px-2 text-xs text-slate-300" /></label>;
export default IntelligenceCenter;
