import { useCallback, useEffect, useState } from "react";
import { Beaker, BrainCircuit, CheckCircle2, Play, RefreshCw, ShieldCheck, XCircle } from "lucide-react";
import api from "../services/api";
import { useAuth } from "../hooks/useAuth";

const inputClass = "h-10 w-full rounded-lg border border-slate-800 bg-slate-950 px-3 text-xs text-slate-300";
const metric = (value) => value == null ? "—" : `${(Number(value) * 100).toFixed(1)}%`;
const MLLab = () => {
    const { hasPermission } = useAuth(); const [runs, setRuns] = useState([]); const [models, setModels] = useState([]); const [modules, setModules] = useState([]);
    const [module, setModule] = useState("GHOSTTRACE"); const [engine, setEngine] = useState("NODE"); const [pythonAvailable, setPythonAvailable] = useState(false); const [sampleCount, setSampleCount] = useState(800); const [seed, setSeed] = useState(1701);
    const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState("");
    const load = useCallback(async () => { try { setLoading(true); setError(""); const [response, health] = await Promise.all([api.get("/intelligence"), api.get("/intelligence/ml/health")]); setRuns(response.data?.trainingRuns || []); setModels((response.data?.models || []).filter((item) => item.learningType === "TRAINED_MODEL")); const choices = response.data?.mlModules || []; const available = Boolean(health.data?.available); setPythonAvailable(available); setEngine((current) => available && current === "NODE" ? "PYTHON" : current); setModules(choices); setModule((current) => choices.includes(current) ? current : choices[0] || "GHOSTTRACE"); } catch (requestError) { setError(requestError.response?.data?.message || "Failed to load ML Lab"); } finally { setLoading(false); } }, []);
    useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer); }, [load]);
    const run = async (request) => { try { setBusy(true); setError(""); setMessage(""); const response = await request(); setMessage(response.data?.message || "Operation complete"); await load(); } catch (requestError) { setError(requestError.response?.data?.message || "ML operation failed"); } finally { setBusy(false); } };
    return <div className="space-y-5">
        <div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl border border-purple-400/20 bg-purple-400/10"><BrainCircuit className="h-5 w-5 text-purple-300" /></div><div><h1 className="text-2xl font-bold text-white">ML Training Lab</h1><p className="mt-1 text-sm text-slate-400">Reproducible labelled simulation, held-out evaluation and deployable model artifacts</p></div></div><button onClick={load} className="flex items-center gap-2 rounded-lg border border-slate-800 bg-slate-900 px-3 py-2 text-xs text-slate-300"><RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} /> Refresh</button></div>
        {error && <div className="rounded-xl border border-red-400/20 bg-red-400/5 p-3 text-sm text-red-300">{error}</div>}{message && <div className="rounded-xl border border-emerald-400/20 bg-emerald-400/5 p-3 text-sm text-emerald-300">{message}</div>}
        <div className="rounded-xl border border-purple-400/15 bg-purple-400/[0.03] p-5"><div className="grid gap-3 md:grid-cols-5"><Field label="Engine"><select value={engine} onChange={(event) => setEngine(event.target.value)} className={inputClass}><option value="NODE">Node baseline</option><option value="PYTHON" disabled={!pythonAvailable}>Python specialized{pythonAvailable ? "" : " (offline)"}</option></select></Field><Field label="Module"><select value={module} onChange={(event) => setModule(event.target.value)} className={inputClass}>{modules.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Samples (100–5000)"><input type="number" min="100" max="5000" value={sampleCount} onChange={(event) => setSampleCount(Number(event.target.value))} className={inputClass} /></Field><Field label="Reproducible seed"><input type="number" value={seed} onChange={(event) => setSeed(Number(event.target.value))} className={inputClass} /></Field>{hasPermission("fleet-learning:manage") && <button disabled={busy} onClick={() => run(() => api.post("/intelligence/ml/train", { module, engine, sampleCount, seed }))} className="mt-5 flex h-10 items-center justify-center gap-2 rounded-lg border border-purple-400/20 bg-purple-400/10 px-3 text-xs text-purple-200"><Play className="h-3.5 w-3.5" /> Train + evaluate</button>}</div><p className="mt-3 text-[10px] text-slate-500">Python service: {pythonAvailable ? "online" : "offline/not configured"} · 75% training / 25% unseen holdout · deployment gate: precision ≥ 90%, recall ≥ 85%.</p></div>
        <div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><section className="rounded-xl border border-slate-800 bg-slate-950/70"><div className="border-b border-slate-800 p-4"><h2 className="text-sm font-semibold text-white">Training runs</h2></div>{!runs.length ? <p className="p-12 text-center text-sm text-slate-600">No training runs yet.</p> : <div className="divide-y divide-slate-800/60">{runs.map((runItem) => <div key={runItem._id} className="p-4"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2">{runItem.status === "PASSED" ? <CheckCircle2 className="h-4 w-4 text-emerald-400" /> : <XCircle className="h-4 w-4 text-red-400" />}<div><p className="text-sm font-semibold text-slate-200">{runItem.module} · {runItem.runId}</p><p className="mt-1 text-[10px] text-slate-600">{runItem.dataset?.sampleCount} labelled samples · seed {runItem.seed} · {runItem.durationMs} ms</p></div></div><span className={`rounded-full border px-2 py-1 text-[9px] ${runItem.status === "PASSED" ? "border-emerald-400/20 bg-emerald-400/10 text-emerald-300" : "border-red-400/20 bg-red-400/10 text-red-300"}`}>{runItem.status}</span></div><div className="mt-3 grid grid-cols-4 gap-2"><Metric label="Precision" value={metric(runItem.metrics?.precision)} /><Metric label="Recall" value={metric(runItem.metrics?.recall)} /><Metric label="F1" value={metric(runItem.metrics?.f1)} /><Metric label="Accuracy" value={metric(runItem.metrics?.accuracy)} /></div><p className="mt-2 truncate font-mono text-[9px] text-slate-700">Dataset SHA-256 {runItem.dataset?.hash}</p></div>)}</div>}</section>
            <section className="rounded-xl border border-slate-800 bg-slate-950/70"><div className="border-b border-slate-800 p-4"><h2 className="text-sm font-semibold text-white">Model registry</h2></div><div className="space-y-3 p-4">{!models.length && <p className="py-8 text-center text-xs text-slate-600">No trained artifacts.</p>}{models.map((model) => <div key={model._id} className="rounded-lg border border-slate-800 bg-slate-900/30 p-3"><div className="flex justify-between gap-2"><div><p className="text-xs font-semibold text-slate-200">{model.modelKey} v{model.version}</p><p className="mt-1 text-[10px] text-slate-600">{model.artifact?.algorithm || "LOGISTIC_REGRESSION_GRADIENT_DESCENT"} · {model.artifact?.featureNames?.length || 0} features</p></div><span className="h-fit rounded-full border border-cyan-400/20 bg-cyan-400/10 px-2 py-1 text-[9px] text-cyan-300">{model.status}</span></div><p className="mt-3 text-[10px] text-slate-400">Precision {metric(model.validation?.precision)} · Recall {metric(model.validation?.recall)}</p><p className="mt-2 text-[10px] text-slate-600">{model.modelCard?.purpose}. {model.modelCard?.limitations?.[0]}</p>{model.status === "VALIDATED" && hasPermission("fleet-learning:manage") && <button disabled={busy} onClick={() => run(() => api.post(`/intelligence/learning/${model._id}/activate`))} className="mt-3 flex items-center gap-1 rounded border border-emerald-400/20 px-2 py-1 text-[10px] text-emerald-300"><ShieldCheck className="h-3 w-3" /> Activate fleet-wide</button>}<p className="mt-2 truncate font-mono text-[9px] text-slate-700">Artifact {model.artifactHash}</p></div>)}</div></section></div>
        <div className="rounded-xl border border-amber-400/15 bg-amber-400/[0.03] p-4 text-xs text-amber-200"><div className="flex gap-2"><Beaker className="mt-0.5 h-4 w-4 shrink-0" /><p>This is genuine supervised baseline training, but the dataset is simulated. Production claims require real labelled trials; PRD-specialized LSTM, autoencoder and XGBoost runtimes are recorded in each model card as remaining work.</p></div></div>
    </div>;
};
const Field = ({ label, children }) => <label><span className="mb-2 block text-[10px] uppercase text-slate-500">{label}</span>{children}</label>;
const Metric = ({ label, value }) => <div className="rounded border border-slate-800 bg-slate-950 p-2"><p className="text-[9px] uppercase text-slate-600">{label}</p><p className="mt-1 text-xs font-semibold text-slate-200">{value}</p></div>;
export default MLLab;
